[versions]
autoService = "1.0.1"
kotlin = "1.9.21"
kspVersion = "1.9.21-1.0.15"

android-build-gradle = "7.4.0"

[libraries]
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }

kspApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kspVersion" }


[plugins]
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }

